"""empty message

Revision ID: 0628828dc732
Revises: 9516b7fe4a51
Create Date: 2023-06-15 18:55:44.494479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0628828dc732'
down_revision = '9516b7fe4a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    op.drop_table('favorite')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('post_name_of_creation_key', type_='unique')
        batch_op.drop_column('file_name')
        batch_op.drop_column('name_of_creation')
        batch_op.drop_column('media_type')
        batch_op.drop_column('description')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_post_id_fkey', 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name_of_creation', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('post_name_of_creation_key', ['name_of_creation'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='favorite_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.drop_table('favorites')
    op.drop_table('comment')
    # ### end Alembic commands ###
