"""empty message

Revision ID: 9516b7fe4a51
Revises: cb4bbe34fe57
Create Date: 2023-06-15 17:04:47.051576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9516b7fe4a51'
down_revision = 'cb4bbe34fe57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    op.drop_table('comments')
    # ### end Alembic commands ###
